export function createDemoProjectFiles(): Record<string, string> {
  return {
    ".gitignore": [
      "node_modules/",
      "coverage/",
      ".commitron-demo/runtime/",
      "",
    ].join("\n"),
    "package.json": JSON.stringify(
      {
        name: "commitron-university-demo",
        version: "1.0.0",
        private: true,
        type: "module",
        scripts: {
          test: "bun test",
          "demo:scenario": "bun run .commitron-demo/scenario-runner.ts",
          "demo:reset": "bun run .commitron-demo/scenario-runner.ts reset",
        },
      },
      null,
      2,
    ) + "\n",
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ESNext",
          module: "ESNext",
          moduleResolution: "bundler",
          strict: true,
          noEmit: true,
        },
        include: ["src", "tests"],
      },
      null,
      2,
    ) + "\n",
    "README.md": [
      "# OTP Store",
      "",
      "A small TypeScript storefront used for the Commitron university demonstration.",
      "",
      "## Commands",
      "",
      "```bash",
      "bun test",
      "bun run demo:scenario ask",
      "```",
      "",
    ].join("\n"),
    "DEMO_GUIDE.md": demoGuide(),
    "src/index.ts": [
      'export { calculateCartTotal } from "./cart.ts";',
      'export { createSession } from "./auth/session.ts";',
      "",
    ].join("\n"),
    "src/cart.ts": [
      "export interface CartItem {",
      "  price: number;",
      "  quantity: number;",
      "}",
      "",
      "export function calculateCartTotal(items: CartItem[]): number {",
      "  return items.reduce((total, item) => total + item.price * item.quantity, 0);",
      "}",
      "",
    ].join("\n"),
    "src/auth/session.ts": [
      "export interface Session {",
      "  email: string;",
      "  createdAt: Date;",
      "}",
      "",
      "export function createSession(email: string): Session {",
      "  return { email, createdAt: new Date() };",
      "}",
      "",
    ].join("\n"),
    "tests/cart.test.ts": [
      'import { expect, test } from "bun:test";',
      'import { calculateCartTotal } from "../src/cart.ts";',
      "",
      'test("calculates the cart total", () => {',
      "  expect(calculateCartTotal([{ price: 12, quantity: 2 }])).toBe(24);",
      "});",
      "",
    ].join("\n"),
    "docs/setup.md": [
      "# Local setup",
      "",
      "Install Bun, then run `bun test` from the repository root.",
      "",
    ].join("\n"),
    ".commitron-demo/marker.json": JSON.stringify(
      {
        kind: "commitron-university-demo",
        version: 1,
      },
      null,
      2,
    ) + "\n",
  };
}

function demoGuide(): string {
  return [
    "# Commitron presentation guide",
    "",
    "This repository is disposable. Prepare a checkpoint, then launch the real",
    "`commitron` command from this directory.",
    "",
    "## Suggested order",
    "",
    "### 1. Ask",
    "",
    "```bash",
    "bun run demo:scenario ask",
    "commitron",
    "```",
    "",
    'Try “show me what changed”, “stage the cart files”, and',
    '“undo my last commit but keep the changes”.',
    "",
    "### 2. Commit",
    "",
    "```bash",
    "bun run demo:scenario commit",
    "commitron",
    "```",
    "",
    "Open Commit and review how authentication, tests, cart behavior, and",
    "documentation are organized into meaningful commits.",
    "",
    "### 3. Branch",
    "",
    "```bash",
    "bun run demo:scenario branch",
    "commitron",
    "```",
    "",
    'Try “add account recovery with one-time codes”.',
    "",
    "### 4. Explain",
    "",
    "```bash",
    "bun run demo:scenario explain",
    "commitron",
    "```",
    "",
    "Open Explain and compare staged, unstaged, and all tracked changes.",
    "",
    "### 5. Fix Error",
    "",
    "```bash",
    "bun run demo:scenario fix-error",
    "git push",
    "commitron",
    "```",
    "",
    "Copy the real non-fast-forward failure into Fix Error. The remote is local",
    "and offline; no Git hosting account is involved.",
    "",
    "## Recovery",
    "",
    "`bun run demo:reset` restores the clean baseline. Every scenario also starts",
    "from that baseline automatically.",
    "",
    "Warning: scenario commands intentionally discard changes, but only after",
    "verifying this generated repository's safety marker and exact Git root.",
    "",
  ].join("\n");
}
