export function createDemoProjectFiles(): Record<string, string> {
  return {
    ".gitignore": [
      "node_modules/",
      "coverage/",
      ".commitron-demo/runtime/",
      "",
    ].join("\n"),
    "package.json": JSON.stringify(
      {
        name: "commitron-university-demo",
        version: "1.0.0",
        private: true,
        type: "module",
        scripts: {
          test: "bun test",
          "demo:scenario": "commitron demo scenario",
          "demo:reset": "commitron demo reset",
        },
      },
      null,
      2,
    ) + "\n",
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ESNext",
          module: "ESNext",
          moduleResolution: "bundler",
          strict: true,
          noEmit: true,
        },
        include: ["src", "tests"],
      },
      null,
      2,
    ) + "\n",
    "README.md": [
      "# OTP Store",
      "",
      "A small TypeScript storefront used for the Commitron university demonstration.",
      "",
      "## Commands",
      "",
      "```bash",
      "bun test",
      "commitron demo scenario ask",
      "```",
      "",
    ].join("\n"),
    "src/index.ts": [
      'export { calculateCartTotal } from "./cart.ts";',
      'export { createSession } from "./auth/session.ts";',
      "",
    ].join("\n"),
    "src/cart.ts": [
      "export interface CartItem {",
      "  price: number;",
      "  quantity: number;",
      "}",
      "",
      "export function calculateCartTotal(items: CartItem[]): number {",
      "  return items.reduce((total, item) => total + item.price * item.quantity, 0);",
      "}",
      "",
    ].join("\n"),
    "src/auth/session.ts": [
      "export interface Session {",
      "  email: string;",
      "  createdAt: Date;",
      "}",
      "",
      "export function createSession(email: string): Session {",
      "  return { email, createdAt: new Date() };",
      "}",
      "",
    ].join("\n"),
    "tests/cart.test.ts": [
      'import { expect, test } from "bun:test";',
      'import { calculateCartTotal } from "../src/cart.ts";',
      "",
      'test("calculates the cart total", () => {',
      "  expect(calculateCartTotal([{ price: 12, quantity: 2 }])).toBe(24);",
      "});",
      "",
    ].join("\n"),
    "docs/setup.md": [
      "# Local setup",
      "",
      "Install Bun, then run `bun test` from the repository root.",
      "",
    ].join("\n"),
    ".commitron-demo/marker.json": JSON.stringify(
      {
        kind: "commitron-university-demo",
        version: 1,
      },
      null,
      2,
    ) + "\n",
  };
}
